---
- name: Set runzero_explorer_path
  ansible.builtin.set_fact:
    runzero_explorer_path: "{{ runzero_explorer_nix_path if ansible_os_family in ['Debian', 'RedHat', 'Darwin'] else runzero_explorer_windows_path }}"

- name: Set architecture mapping for runzero-explorer
  ansible.builtin.set_fact:
    runzero_explorer_arch_map:
      x86_64: amd64
      aarch64: arm64

- name: Determine runzero-explorer binary architecture
  ansible.builtin.set_fact:
    runzero_explorer_arch: "{{ runzero_explorer_arch_map[ansible_architecture] }}"
  when: ansible_os_family in ['Debian', 'RedHat', 'Darwin', 'Windows']

- name: Check if RUNZERO_DOWNLOAD_TOKEN is set
  ansible.builtin.fail:
    msg: "The RUNZERO_DOWNLOAD_TOKEN environment variable must be set."
  when: lookup('env', 'RUNZERO_DOWNLOAD_TOKEN') is not defined or lookup('env', 'RUNZERO_DOWNLOAD_TOKEN') == ""

- name: Set the unique token
  ansible.builtin.set_fact:
    runzero_explorer_unique_token: "{{ lookup('env', 'RUNZERO_DOWNLOAD_TOKEN') }}"

- name: Create the directory for the runzero-explorer binary
  ansible.builtin.file:
    path: "{{ runzero_explorer_path | dirname }}"
    state: directory
    mode: '0755'
  become: true

- name: Include tasks for Unix-like systems
  ansible.builtin.include_tasks: unix.yml
  when: ansible_os_family in ['Debian', 'RedHat', 'Darwin']

- name: Include systemd tasks
  ansible.builtin.include_tasks: systemd.yml
  when: ansible_os_family in ['Debian', 'RedHat'] and runzero_explorer_systemd_enabled | bool

- name: Include tasks for Windows
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
