---
namespace: l50
name: bulwark
version: "1.0.0"
readme: README.md
authors:
  - Jayson Grace <techvomit.net>
description: Install and configure defensive security tools and utilities used regularly.
license_file: "LICENSE"
tags: [runzero]
repository: https://github.com/l50/ansible-collection-bulwark
issues: https://github.com/l50/ansible-collection-bulwark/issues
