---
collections:
  - name: amazon.aws
    version: 9.1.0
  - name: ansible.windows
    version: 2.6.0
  - name: community.docker
    version: 4.2.0
  - name: community.general
    version: 10.1.0
  - name: cowdogmoo.workstation
    version: 1.9.4
